import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/layout/navbar";
import Footer from "../components/layout/footer";
import Providers from "./providers";
import { Suspense } from "react"; // 🚀 Import Suspense

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          {/* 🚀 Wrap Navbar in Suspense so useSearchParams does not break static pages like 404 */}
          <Suspense fallback={<div className="h-20 w-full bg-gray-900 border-b border-gray-100" />}>
            <Navbar />
          </Suspense>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}